travis:
  secure:
    BINSTAR_TOKEN: tdGE4bOhniw2RtRVkJbbeabb/1nwW9z6s9P7QOsLWpMwYqtk3iP5kiyUCrhoClgsaouluzDEJ1VgZts3z5Ys+XpQ5eShK+hMJ6dT8ToBOTmsRT+UU162giX/dcDJcsRwXVZOWuVeBtNxlW4S1gSKIIgpEp7nXheCTvTD9sagjFDtavVhnJ/OqLeI56eX3QPkK7HG7ipapkx4LJPAh0hJCEb7GSWQOAWrUYC/qew9bYyBB3xj4nZrASGvAdoke0EHENGVdMY7PTY8C03aoqX/NVKi+cu30A5sCOOLC1hFsZx/yoMSgPJSGdUn1QvMM6cC0BN+etjR0Yase7gzT9Jw7INymmRgwCo5GRIGJ22ycPwzGEuimKPf7O1mU+UJBAWLZxjRLcqeI/hMPPo129T/Ihlu2J1vzmXr0/nZksNfVYzIuMX7pfksijilmsaf5ALi5U5tkEdg0vBq0TP1kn7ofT4hkhpE/SgqoNolICXrVOWcCu0BXjbznnv8+LJKGN7QY0houUpWwH6dHEdYXzuaCJ/cLX+dlard175JdlUKTPf9C0oOVasxMv4X12s6ODT7OitY6pMQ6bGrj9EY1ZK2NdcpDfE1bgHp3+MuOOEqCpSEvYjoNElq7k3PBfTSXrzDmFwjyz6GMWZHaWqPBFnq+hE7ivrV55CgHJayrSw0Yog=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
