travis:
  secure:
    BINSTAR_TOKEN: PyNbbweO6NrKf3UVf/Ej90vm9f1U4NLiD54EPoLm034ofgwhoGjQjbvyqWkwNAwXaWEATseDioez7PpVmz9BKdzN7HDk6/XGa0AxD79OqOtMajUpoG9r1i1D02ES7Jg2o1LRdN/geNgb+Bk4g7zL/e7kX4p/SXLCa69SO7ewSEeExkEZTpXkg3rHsumendrzifZ/kIIpBtD4xzvtCUfHzIudDMibFohck1lTEKviF2h/f3yoTK4l3CpcQpPJV++IOJCdVPGFbBuBDtW1Yas0j7NK3H2VVSeJ6+E3MZIobTC/8vTXf3/QQfL3dOWywlwBzFtocrdlpHSFSFxJh2MvzTambVAuxwozpecWJ0BtV2Jbs2C20gsA8lex3ibCh3H+0ttZmCaw+nI1uiVTJyl2o4fUmNFdL/lNN7oqseTz200GNnt4BVt+dhb9kuk87/kKBDsZGu3AaPsAsUbQPY0FL+QYHdYj9y/NsW9QvU/rVOTPeiSlHBMDX6c5M4isrCVw3YuWByX0OlhnvhJECt5CK0eUS0MV/6RImEjOGO/GTcIB7mwt4VC00cMZUYAZtT0Z2+j1u4xKUFss9ikbG80pqRfU7q7pXw0YflysIBLOb+cdVwRuiJZs3yag4PLkp+VYmojF5EQ+Axc37qO7AuQcJkrdsB6b0PMNgAj8SHHRffM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
