travis:
  secure:
    BINSTAR_TOKEN: xtzSUXpO3TwYahdniLit8lvyDujbUDKN68AeQsJ2OH2yQDZO4Hpv29fofFRs8cf/+YSNuqwFubff1KwMijIkbIUgLFEmQH9HUBsb0fdlTwR8X9ZGdpeGRlmaBP8EoBvATw6QcTkhNG6WUieAcKITYq7iq8NvMy5rshVpKY7efDZZQBigCKCr6hIz+9QxAKpz/JJZtFQHR9o1t/273vdLWXH+tm54wDcKRJBNzMjC4CQ0lfRcmbszHlqA3bYHOiCoeTWb1HYogxnJr0mPy/TAr09fmOgdH3rtLX1m95/jjQ54jDgWriNhGjG2Gc1g3bwMRBOhAAtZdsZ4KomK9Obghr4sywKw227x+fQ1+ebHRNlRXUGqJyeu6YP3gXC+e4HVb8uaoVjcTr97N17nfDeg4WgiYHnB70EIHZQPx4veffgmZOjfyIOEThJNdmW12JodEPMpTcfEzx4Obo18b1j6S8XXpjRjhOWKODM30mhZgBiLb9ybFUpeavopRW8/VLVXrQuZhqfzg/9F9n6H6GfTEIq5IF6CBpYVBRf399SRv6QUhKjsoJYzD+R8VbQZ21f2j7Sg051pP3iUC91c0IerZbixKVpg1VuWwJ5tNuJmPU/zfWXSbmn0UWip5gBO+y1Mpi6qzApd3BxHn8j6cX8MNaFq4KbOIdS1JmnuoR8GDWA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
