travis:
  secure:
    BINSTAR_TOKEN: I0WmePzf5bxlDP7X8iKLPgw0oKShNB8EHOgOKEUcH72BP+U3bhnzzm1DMtFUBw5lRwMYc1vwf2TObWtJRCpAuE+g7bNWwXU0KBEa83kpRk0vONdc8Tp3SC3o/QutePmCuW/nmN8WWSESmfwGKmtAM2XGuTZfKW+pfFcn3msAMq3G+reTr6JUuPRDUzOgwoa0JfL/FNGnSe3T1oFi7kaOF6sqArkKe4Wixc2RFM5bPv6yORbxdQ1k4AUNl6gVXFf2MF6zVcCcXjwPtf9utfPnlqoO1Gq2kUXxOeTbMA+dRs6dnyzPQXRl660jd/DRDjlczlPG1JY7833j+IK3mq3ol6aWNJSx3cU9AgagUU4uFIX14pIzEdLuhrOcGTls1Uz1b+dUlOri19UKDNPDmZRSmqFPLmgFjs3WGkh1hJ8ZdKyZDV2f42ryvwW/bT91MSt22EkAJvOX5edTLirM1+F6NPLJjzNMN0ZTo94mZLKhpehxsF2qTzxN1v0wm6C1mSz1N6CaEbpVrLS6zsiSfVHB16NNru+D5Lp1TFIfALq/N3T/KI+Hz5mld1R1PVpJLt2wKy8go3iZP17tCR0WCZvHs8MzO6Y4NOdvf5ztC0GMit6y2P8yft2HnL/LMX77U4INJI0UxCmFmXgQVx7uLsC/GyTUk9omDEXexe0u/SGplUs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
